### ISSUE TITLE
qp-prob

### ISSUE THREAD

**Issue by cmbant** [LSSTDESC/sacc#104]
The qp module only appears to be loaded dynamically, and likely is not needed in e.g. CMB use cases. Suggest removing qp-prob from requirements? (or at least make it optional)
On Windows, I can't install sacc with pip due to issue compiling pytdigest which is a requirement of qp-prob.

**Comment by joezuntz** [comment]
Twenty five years and you're still the only cosmologist using Windows, Antony!

But yes, making this an optional requirement makes sense.  I can add an "all" installation option.

**Comment by cmbant** [comment]
Thanks! "tables_io" seems to be also used be loaded dynamically but not listed in requirements. 
There are some small typos/refactors you might want to check at https://github.com/LSSTDESC/sacc/compare/master...cmbant:sacc:master

There are other instances of unused `quantity = table.meta.get('SACCQTTY', 'generic')` , and probably a missing "return" in _hg_ls_files_and_dirs (if ret)?

**Comment by joezuntz** [comment]
Version 0.14 is now on pypi and has the both qp-prob and numpydoc as optional dependencies.  You can install with sacc[all], sacc[doc], or sacc[qp].

I'm also doing a PR for your other tweaks - many thanks. Though I think _hg_ls_files_and_dirs is in the library that gets used to do the versioning, not sacc itself.
