### ISSUE TITLE
sortTracers() is broken

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/sacc#11]
The `SACC.sortTracers()` function found [here](https://github.com/LSSTDESC/sacc/blob/master/sacc/sacc.py#L103) returns a tuple of information regarding a SACC's tracers in a sorted form. The problem is that the function assumes that all tracers are used in 2pt statistics. It is currently not compatible with cluster number counts, and would also fail if we ever had a 3+pt statistic.

Some thought must go into what to do about this, since TJPCosmo currently uses this function when creating DataSet objects.

**Comment by tmcclintock** [comment]
This is fixed in the #8 PR, for the case of cluster number counts.

**Comment by damonge** [comment]
Closing, I guess
