### ISSUE TITLE
refactor/decide on API

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/sacc#20]
To do:
- [ ] come up with API examples
- [ ] define all the use cases
- [ ] decide on stuff below

We agreed to decide on an API and/or format for:

- correlation functions
- covariances
- power spectra
- redshift distributions
- window functions
- Bandpass information. Currently hacked by using Tracer.z and Tracer.Nz, but this could be done in a more sophisticated manner.
- cluster counts
- cluster lensing
- SNe data

Some of this exists and other parts do not yet. 

We also want APIs for:
- quick cov. matrix inversions
- easily access all elements of the data vector containing one particular type of correlation (e.g. EE or BB or +R etc.)
- easily access all elements of the data vector associated to one particular pair of tracers.
- standards for diffing data and/or determining if two datasets are the same
- Extracting the angle values, mean and, covariance of specific bin pairs as numpy arrays
- Masking out scales in specific bins or globally
- Masking out entire bin pairs
- Extracting the distribution for a named tracer
- Attaching a covariance/precision to an incomplete sacc object
- Adding a new bin pair to an incomplete sacc object
- Making a copy of a sacc object
- Building up a sacc object progressively from e.g. rows in a table
- Plotting data (?) This is optional.
- unique ids
- checksumming
- **your thing here**

**Comment by beckermr** [comment]
Yep the api has quite a bit of these things already. The goal here is to take stock of what is there, figure out what we want to do in addition, and make sure when we add everything it is all coherent.

**Comment by rmjarvis** [comment]
I have an [issue in TreeCorr](https://github.com/rmjarvis/TreeCorr/issues/66) to support outputting to SACC format, but it sounds like maybe this isn't really stable yet.  Especially given that there aren't any releases or tags for this repo yet.

Please ping me on that issue when the API settles down and you think it would be worth it for me to work on that.  I don't want to do something there if it will end up having to be redone when you change stuff over here.

**Comment by joezuntz** [comment]
This issue has been dealt with in the v 0.2.0 release.
