### ISSUE TITLE
relicense under BSD-3-clause

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/sacc#22]
We want to relicense under BSD-3-clause. All current contributors need to agree. This includes

- [x] @slosar 
- [x] @damonge 
- [ ] @adam-broussard 
- [x] @tmcclintock 
- [x] @HironaoMiyatake 
- [x] @joezuntz 
- [x] @jeremyneveu 
- [x] @fjaviersanchez 

Please respond to this issue saying you agree. Once we have all eight I will make a PR.

**Comment by slosar** [comment]
Agree.

**Comment by tmcclintock** [comment]
And my axe.



yes I agree

**Comment by joezuntz** [comment]
Yup

**Comment by fjaviersanchez** [comment]
Agreed

**Comment by jeremyneveu** [comment]
Ok

**Comment by beckermr** [comment]
@adam-broussard Can you please agree to relicensing this repo?

**Comment by beckermr** [comment]
@HironaoMiyatake Can you please agree to relicensing this repo?

**Comment by beckermr** [comment]
@slosar @damonge help bugging these last two ppl would be great!

**Comment by HironaoMiyatake** [comment]
Agreed. Sorry for this late reply!

**Comment by beckermr** [comment]
Thank you!

**Comment by beckermr** [comment]
@adam-broussard Can you respond to this?

**Comment by beckermr** [comment]
If we don't hear back soon @damonge, then I think we should just do it.

**Comment by adam-broussard** [comment]
Agree!

**Comment by beckermr** [comment]
Thank you!
