### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/sacc#33]
Hi @slosar @joezuntz - I wanted to point out that it would be useful to update the repo README to reflect the state of the code given that the repo is public, especially if you're starting to look for more users (is the code ready for broader usage? is it a DESC product? how to get help? etc.)  The Pub Board collected a [useful set of guidelines](https://confluence.slac.stanford.edu/download/attachments/215859451/Guidelines%20for%20DESC%20Repositories.pdf?version=1&modificationDate=1528306924000&api=v2) to help with this, so hopefully it should be an easy fix.

**Comment by joezuntz** [comment]
HI Rachel,

Thanks - I'll do that! 

Except for one thing - including this sentence is a a profoundly bad idea:

>  if you wish to use the code outside DESC please contact the developers.

The license makes it very clear this is not formally necessary, and if we want to encourage use of this format it would be a deeply stupid thing to request.

**Comment by slosar** [comment]
@joezuntz I fully agree with your comment on outside DESC use.

**Comment by joezuntz** [comment]
Okay, readme updated.  Also I submitted the code to ASCL so there would be something to cite.

**Comment by rmandelb** [comment]
Thanks for updating the README to clarify that this code is released, with readthedocs documentation and citation via ASCL!  

I agree the sentence you highlighted from the guidelines is not relevant for released DESC code (in a Pub Policy and GitHub repo access sense), and noted that to Seth for the next PB update of the guidelines.  The guidelines themselves have gone through a few iterations as DESC policy has evolved, and as they’ve been updated to include the various possible combinations that exist in practice: unreleased/released code in public repositories, unreleased code in private repositories, different LICENSE options, etc. so I’m guessing that one of those permutations was overlooked as this evolved.
