### ISSUE TITLE
using FullCovariance subclass

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/sacc#50]
Hello, I'm trying to create a SACC object with a full covariance matrix, and am running into trouble. Can someone specify how one is to construct the covariance matrix? The [description in the docstring](https://github.com/LSSTDESC/sacc/blob/92ff4a4da9867031a1b1b7aa17f8057ce91ebc58/sacc/covariance.py#L142-L143) says that the matrix is supposed to be `n x n` but the `n` is not described. Later, [in the description of the `covmat` attribute](https://github.com/LSSTDESC/sacc/blob/92ff4a4da9867031a1b1b7aa17f8057ce91ebc58/sacc/covariance.py#L150-L151), it says its an array of shape `(size x size)`. Now, if this `size` is supposed to be the [`expected size`](https://github.com/LSSTDESC/sacc/blob/92ff4a4da9867031a1b1b7aa17f8057ce91ebc58/sacc/sacc.py#L209), I really don't understand what's going on since the `size` of `(size x size)` array is not `size` .. 

I tried to play around with the various inputs to see if I can figure out what is expected to be passed to the `FullCovariance` subclass. I only get things to work *if* I use 9 ell-samples and pass all (nine) correlations for a 3-bin case. Then, the `expected size` is 81 (presumably len(ell-samples) x types of cls) =  9 x 9), and I can make my full 3 x 3 x 9 covariance matrix to be 9 x 9.

However, I don't know how to construct for a 2D array for any other case, e.g., if I have 99 ell-samples, the expected size is 891 .. which is not a perfect square :(

I'd really appreciate some help. Thank you!

Also, I'm quite sure that there's a bug in the class when it comes to calculating the size of the matrix: if the covariance matrix is a 2D array, the *size* cannot be `matrix.shape[0]` -- which is what is calculated [here](https://github.com/LSSTDESC/sacc/blob/92ff4a4da9867031a1b1b7aa17f8057ce91ebc58/sacc/covariance.py#L155). I think it needs to be replaced with `matrix.size`.

p.s. I realize I am using v0.2 but as far as I can tell, I will have the same question for v0.3.

**Comment by joezuntz** [comment]
Hi Humna.

You shouldn't need to manually instantiate a covariance object, unless you're doing something fairly niche.  When building up a `Sacc` object you can just use the `add_covariance`, which I see you've seen.

The idea is that you call `add_covariance` after adding all the data points already, with `add_data_point`.  Then if you've passed in `n` data points then your matrix should be shaped as `nxn`.

The `size` attribute of `FullCovariance` objects is `n`, not `n^2`.

Hope that helps?
Joe

**Comment by humnaawan** [comment]
hi @joezuntz thanks! so i wasn't trying to instantiate `FullCovariance` directly at first but it is nevertheless instantiated by the [`BaseCovariance.make`](https://github.com/LSSTDESC/sacc/blob/92ff4a4da9867031a1b1b7aa17f8057ce91ebc58/sacc/sacc.py#L207) function unless a `BaseCovariance` object is passed to `add_covariance` (which I couldn't get to work either).

now, as for adding data to the `sacc` object,  since i'm working with spectra in redshifts bins, i was using `add_tracer` and then `add_ell_cl` -- hence my confusion r `n`. is it just that i need to add individual `ell` separately?

in case its helpful, here's my code for diagonal covariance matrix (which works):
```
# add tracers
for i in range(nzbins):
    sacc_obj.add_tracer('NZ', 'bin_%s' % i, z_arr, dndz[i])

# attempt at diagonal covariance
diag_variance = []
for i in range(nzbins):
    bin1_name = 'bin_%s' % i
    # ----
    # bin the spectra
    cl = []
    for m, M in window_ranges:
        cl.append( np.mean(c_ells[i][i][m:M]) )
    cl = np.array(cl)    
    # ----
    # add cls
    sacc_obj.add_ell_cl(galaxy_density_cl, bin1_name, bin1_name,
                            effective_ell, cl, window=windows)
    # variance
    fsky = 0.35
    var = 2 / (fsky * (2 * effective_ell + 1 )) * cl**2   
    diag_variance.append( var )
        
# works
diag_variances = np.concatenate(diag_variance)
sacc_obj.add_covariance(diag_variances)
```

and for non-diagonal matrix (which doesn't work)
```
# add tracers
for i in range(nzbins):
    sacc_obj.add_tracer('NZ', 'bin_%s' % i, z_arr, dndz[i])

# attempt at full covariance
cov_matrix = np.zeros((nzbins, nzbins, len(effective_ell)))

for i in range(nzbins):
    bin1_name = 'bin_%s' % i
    for j in range(nzbins):
        bin2_name = 'bin_%s' % j
        # ----
        # bin the spectra
        cl = []
        for m, M in window_ranges:
            cl.append( np.mean(c_ells[i][j][m:M]) )
        cl = np.array(cl)    
        # ----
        # add cls
        sacc_obj.add_ell_cl(galaxy_density_cl, bin1_name, bin2_name,
                            effective_ell, cl, window=windows)
        # variance
        fsky = 0.35
        var = 2 / (fsky * (2 * effective_ell + 1 )) * cl**2
        cov_matrix[i][j][:] = var
        cov_matrix[j][i][:] = var

# doesn't work:
sacc_obj.add_covariance(cov_matrix)
# or
# sacc_obj.add_covariance(cov_matrix.flatten())
```

**Comment by joezuntz** [comment]
Ah, right.  add_ell_cl is a wrapper around add_data_point which just adds all the data points one by one.  When you get to the cov mat it's the same as if you'd just done lots of add_data_point calls.

So the upshot is that your covariance matrix there is `nbin x nbin x nell`, but should be the complete `ndata x ndata`.  You'll have to reformulate how you construct it.

**Comment by joezuntz** [comment]
Closed as hopefully dealt with - please reopen if useful.
