### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/sacc#59]
It may often be useful to store some arbitrary information about the contents of a sacc file. E.g. author, provenance, simulation used to generate it, random comments, paths to related files. It might be nice for SACC to have a random container (e.g. in the header of the first HDU) that can store a small dictionary with arbitrary metadata. Thoughts?

**Comment by joezuntz** [comment]
Yep, this already exists. You can do:

```
s=sacc.Sacc()
s.metadata['creator'] = 'David'
s.metadata['year'] = 2024
s.metadata['H0'] = 72.0
```
It will get saved in the primary header.

**Comment by damonge** [comment]
ooh, fantastic! I had forgotten about this. Thanks!
