### ISSUE TITLE
Computation concerns

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/sacc#9]
@HironaoMiyatake and I are discussed potentially connecting SACC with [CLMM](https://github.com/LSSTDESC/CLMM) at some point and noticed that [`tracer.py`](https://github.com/LSSTDESC/sacc/blob/cluster_ncounts/sacc/tracer.py) overwrites Python's built in `type()` method, which would be a problem for CLMM.

Also, have folks checked in on the h5py/HPC instability issues in relation to the SACC data format?

**Comment by tmcclintock** [comment]
I don't *think* that this is an issue. I believe the 'type' attribute is scoped to within the `__init__` function. In python 3, objects don't have a `type()` function or a `type` attribute. In other words, the built-in function `type()` is only overridden within the initializer.

For instance, I can do the following:
```python
import sacc

y = [0, 1, 2] # a list
T = sacc.Tracer("my_name", "my_type", None, None) # a tracer object

#print(y.type) #this isn't allowed and gives an error
print(T.type) #this prints "my_type"
```

Also, can you provide a link for the h5py/HPC issues?

**Comment by joezuntz** [comment]
This is now superseded by the new format version 0.2
