### ISSUE TITLE
sacc version 0.11 self-reports as sacc 0.9

### ISSUE THREAD

**Issue by marcpaterno** [LSSTDESC/sacc#96]
The most recent release of sacc (0.11) reports itself to be sacc 0.9; the `__init__.py` file was not updated to reflect the new version number.

**Comment by joezuntz** [comment]
shit, sorry.  Will release a version 0.12

**Comment by marcpaterno** [comment]
Hi Joe,

I’d be happy to fix it. Would you consider naming it 0.11.1, to help indicate there is no API difference from 0.11 ?

--Marc


From: joezuntz ***@***.***>
Date: Tuesday, August 8, 2023 at 8:46 AM
To: LSSTDESC/sacc ***@***.***>
Cc: Marc F Paterno ***@***.***>, Assign ***@***.***>
Subject: Re: [LSSTDESC/sacc] sacc version 0.11 self-reports as sacc 0.9 (Issue #96)

shit, sorry. Will release a version 0.12

**Comment by marcpaterno** [comment]
Hi again,

In response to my own proposal, I found that changing the `__version__` string to 0.11.1 results in a build that gets the installation artifacts labeled as 0.12 anyway. So, never mind my proposal to name it 0.11.1.

--Marc


From: joezuntz ***@***.***>
Date: Tuesday, August 8, 2023 at 8:46 AM
To: LSSTDESC/sacc ***@***.***>
Cc: Marc F Paterno ***@***.***>, Assign ***@***.***>
Subject: Re: [LSSTDESC/sacc] sacc version 0.11 self-reports as sacc 0.9 (Issue #96)

shit, sorry. Will release a version 0.12

**Comment by joezuntz** [comment]
Apologies, I've set it running as v0.12 already, but I agree that would have been more sensible!
